# Generated by Django 6.0.5 on 2026-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
