# Generated by Django 6.0.5 on 2026-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-played_at"]},
        ),
        migrations.AlterField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
