# Generated by Django 6.0.5 on 2026-05-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0002_team_created_at"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played", models.PositiveIntegerField(default=0)),
                ("won", models.PositiveIntegerField(default=0)),
                ("drawn", models.PositiveIntegerField(default=0)),
                ("lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["-points", "-goals_for"],
                "unique_together": {("tournament", "team")},
            },
        ),
    ]
