# Generated by Django 6.0.4 on 2026-05-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_coach_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
