# Generated by Django 6.0.4 on 2026-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_coach_photo_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
