# Generated by Django 6.0.4 on 2026-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_coach_photo_alter_player_photo_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
