# Generated by Django 6.0.4 on 2026-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_coach_description_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
